### ISSUE TITLE
Decoding issues with operator that doesn't use numbers in FROM (Orange.pl)

### ISSUE THREAD

**Issue by kuleszdl** [obsy/sms_tool#1]
SUT: cda9417198f01e9727388265fdaa9919f0e0f560 (self-compiled using LEDE SDK)

First of all - thank you for providing this great tool! It works for me basically, however I observed some decoding/encoding issues when using orange.pl:

    # sms_tool -d /dev/ttyUSB1 -R ussd "*103*#"
    unparsable CUSD response: "Zlecenie zostalo przyjete do realizacji. O jego wyniku poinformujemy Cie osobnym SMSem.", 15

Without using -R, the output is just `unparsable CUSD response: ` without any details.

Now, when reading the received SMS, it seems it can't be decoded:

    # sms_tool -d /dev/ttyUSB1 -f "%Y-%m-%d %H:%M" recv
    MSG: 1
    From: Orange@qc
    Date/Time: 2017-12-31 22:32

    MSG: 2
    From: Orange@
    Date/Time: 2015-06-05 11:05
    Twoje konto zostalo doladowane. Dodatkowo otrzymales bonus na polaczenia z internetem. Masz lacznie 12095,8 MB na polaczenia z internetem wazne do 08.11.2015.

Using the operators `-R` and `-r` it seems there is some content in the message (I don't want to post it here because I don't know if it may contain sensitive data).

Interestingly, the issue does not arise for way older messages from the same operator (where the `FROM` did not contain a name but just a number):

    MSG: 19
    From: 7095
    Date/Time: 2015-11-05 10:02
    W dniu 08.11.2015 konczy sie okres waznosci twojego bonusu na start i za doladowanie. Pozostalo Ci jeszcze 7311 MB do wykorzystania. Szczegoly na www.orange.pl

The examples on the web site also use messages with numbers in the "FROM" field, so I suspect it could be related to that.

Thank you and all the best for the coming year!

**Comment by obsy** [comment]
Send me private email containing:
1. Use picocom, run `at+cusd=1,"*103*#",15`. Show output with all chars
2. output of sms_tool -d /dev/ttyUSB1 -r recv

**Comment by kuleszdl** [comment]
Sent - thank you!

**Comment by obsy** [comment]
SMS output fixed in https://github.com/obsy/sms_tool/commit/d2ef333593d9b947690e6f0b35c9faf812b19517 , https://github.com/obsy/sms_tool/commit/4b6c7790b5240ef01c1ada8c2b5e65049768dcfd and https://github.com/obsy/sms_tool/commit/f4e9824b20ec5325590a103070845a175f860bcb . 

USSD parser should works only for one-line response.
