### ISSUE TITLE
Building packages for Openwrt on Raspberry Pi4b

### ISSUE THREAD

**Issue by finish475** [obsy/sms_tool#10]
Hi sir!
I am a newbie.
I am wanting to use your tool for SierraWireless EM7565 in openwrt 21.02.1 with Raspberry Pi4 router.
I really don't know what materials are needed in combination with your source code to build the sms-tool.ipk file.
Can you give me detailed instructions please?
Thank you very much!

**Comment by obsy** [comment]
Hi,
1. Setup SDK, read this: https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#debianubuntu and https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem
2. Compile sdk for RPI4.
3. go into sources, and
```
mkdir package/sms-tool
cd package/sms-tool
wget https://raw.githubusercontent.com/obsy/packages/master/sms-tool/Makefile
make oldconfig #answer M
make package/sms-tool/compile 
```
