### ISSUE TITLE
Incorrect output of AT command

### ISSUE THREAD

**Issue by vetaldudnik** [obsy/sms_tool#11]
sms_tool produce no output on AT+QTEMP command on my EM12-G modem:

```
root@OpenWrt:~# sms_tool -d /dev/ttyUSB2 at "AT+QTEMP"
AT+QTEMP
root@OpenWrt:~#
```

But if I send this AT command directly to tty port using minicom the output is present:

```
AT+QTEMP
OK

+QTEMP: "xo_therm_buf","33"

+QTEMP: "mdm_case_therm","33"

+QTEMP: "pa_therm1","33"

+QTEMP: "tsens_tz_sensor0","35"

+QTEMP: "tsens_tz_sensor1","35"

+QTEMP: "tsens_tz_sensor2","35"

+QTEMP: "tsens_tz_sensor3","34"

+QTEMP: "tsens_tz_sensor4","35"

```

I think the problem appers because this AT command say OK at first

**Comment by obsy** [comment]
Yes, In EM12/EG18 etc this command works differently than others and data is returned asynchronously. OK/ERROR is an indicator of the end of the command, in this case it is not known when the data will be returned.
