### ISSUE TITLE
Error decoding short pdu

### ISSUE THREAD

**Issue by kkubicki** [obsy/sms_tool#2]
DUT:
Nexx WT3020 (8M) + huawei E3131

SUT:
OpenWrt 19.07-SNAPSHOT, r10949-c56ed72d2b
Package: sms-tool
Version: 2019-08-25-20030ff6-1
Architecture: mipsel_24kc

Test procedure:
1/ Send short SMS with only one letter 'O' to the 3g modem
2/ Receive SMS: sms_tool -d /dev/ttyUSB2 recv

Observation:
MSG: 0
From: 48x
Date/Time: 06/24/20 13:28:52
Test zwrotny

MSG: 1
error decoding pdu 1: 07918405210077F7000B91848XXXXXXXF5000002604231437380014F

Additional info:
Injecting same pdu buffer into the program on Linux platform gives proper result:
$ ./sms_tool -r test
07918405210077F7000B91848XXXXXXXF5000002604231437380014F
$ ./sms_tool test
From: 48XXXXXXXXX
Date/Time: 06/24/20 13:34:37
O

**Comment by obsy** [comment]
Remove msg0 and show me full debug info from msg1.

**Comment by kkubicki** [comment]
Ok, I've deleted msg0, but not sure how to print full debug:
~# sms_tool -d /dev/ttyUSB2 -D recv
MSG: 1
error decoding pdu 0: 07918405210077F7000B91848XXXXXXXF5000002604231437380014F

There is no more info regarding the error.

**Comment by obsy** [comment]
Just don't replace any chars in output. You can send me an email with this.

**Comment by kkubicki** [comment]
Ok, I sent you an e-mail. Thanks!

**Comment by obsy** [comment]
Try this fix: https://github.com/obsy/sms_tool/commit/5f161bf7bf18fc995a519021d64827feb74d4f6a

**Comment by kkubicki** [comment]
Seems that it's working:
MSG: 1
From: 48XXXXXXXX
Date/Time: 06/24/20 13:34:37
O

Many thanks!
