### ISSUE TITLE
TP-Link TL-MR6400 SMS reception does not work

### ISSUE THREAD

**Issue by HyP3r-** [obsy/sms_tool#3]
I have installed OpenWRT on the TP-Link TL-MR6400. Unfortunately SMS reception does not work (the command `sms_tool -d /dev/ttyUSB0 recv` shows nothing). But the SMS sending works.

Output `sms_tool -d /dev/ttyUSB0 status`:
```
Storage type: SM, used: 0, total: 20
```

Output `sms_tool -s ME -d /dev/ttyUSB0 status`:
```
Storage type: ME, used: 0, total: 23
```

What could be the cause of this? What troubleshooting information do you need?

**Comment by obsy** [comment]
Which version of mr6400 is it?
Are you sure you have SMS on the card? Send SMS again and don't take the card out of the modem. You can check manually if there are sms by AT +CMGR command, see https://www.developershome.com/sms/cmgrCommand.asp

**Comment by HyP3r-** [comment]
> Which version of mr6400 is it?

It is the **TP-Link TL-MR6400 v1.0** Version.

> Are you sure you have SMS on the card? Send SMS again and don't take the card out of the modem. You can check manually if there are sms by AT +CMGR command, see https://www.developershome.com/sms/cmgrCommand.asp

I installed socat on the Router and tested some commands (https://openwrt.org/docs/guide-user/network/wan/wwan/at_commands). And it feels like there are really no messages in the storage of the modem:

```
at+cpms=?
+CPMS: ("ME","MT","SM","SR"),("ME","MT","SM","SR"),("ME","MT","SM","SR")

OK
```

```
at+cpms?
at+cpms?
+CPMS: "SM",0,20,"SM",0,20,"SM",0,20

OK
```

```
at+cmgl=?
at+cmgl=?
+cmgl: (0-4)

OK
```

```
at+cmgl=4
at+cmgl=4

OK
```

```
at+cmgr=?
at+cmgr=?

OK
```

```
at+cmgr=0
at+cmgr=0

OK
```

```
at+cmgr=1
at+cmgr=1

OK
```

```
at+cmgr=2
at+cmgr=2

OK
```

```
at+cmgr=3
at+cmgr=3

OK
```

```
at+cmgr=4
at+cmgr=4

OK
```

What do you think?

**Comment by obsy** [comment]
Modem in MR6400 v1 has its own gui. Check if you can see the text message there.

**Comment by HyP3r-** [comment]
What do you mean by GUI? I have OpenWRT on the router. From the Linux point of view I have three ttyUSB devices (ttyUSB0 to ttyUSB2).

I also put the SIM card in my cell phone yesterday and I can receive SMS with it. So it is not the contract.

**Comment by obsy** [comment]
See https://openwrt.org/toh/tp-link/tl-mr6400_v1#lte_module

**Comment by HyP3r-** [comment]
I did not know that there is this web interface. Awesome. A modem with a web interface. You really never stop learning.

But back to the topic: yes, here is my test SMS visible. What can I do now?

![2021-08-15-12-49-56_RemoteDesktopManagerFree](https://user-images.githubusercontent.com/8094242/129475985-a087d2c8-7d33-413e-85fd-cf1666768139.png)

**Comment by obsy** [comment]
Try storage "MT" or "SR". If it does not work - you will not be able to read text messages with AT commands, because they are downloaded by modem gui / android.

**Comment by HyP3r-** [comment]
I have set all three memory areas to "SM" (`AT+CPMS="SM","SM","SM"`) and now it seems to work. Don't need to understand... Thanks for the help.
