### ISSUE TITLE
can receive SMS, cant send sms or ussd

### ISSUE THREAD

**Issue by mashakos** [obsy/sms_tool#6]
I have a tplink mr6400 v5, figured out my usb device is ttyUSB2
`Storage type: ME, used: 3, total: 23`
Unfortunately I can't send USSD codes nor sms messages. Sending ussd gives me "error: retry operation" and sending sms doesnt actually complete
I have tried various combinations of settings with no luck so far.

**Comment by obsy** [comment]
Sorry, never tried on mr6400. Maybe modem required something else to enable or set.

**Comment by mashakos** [comment]
never tried TPLINK TL-MR6400 router?

**Comment by obsy** [comment]
No. Install picocom (opkg update && opkg install picocom), run (picocom -b 115200 /dev/ttyUSB2) and check manually if sending works: https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/at-cmgs-text-mode/

**Comment by mashakos** [comment]
``` picocom -b 9600 /dev/ttyUSB2
picocom -b 9600 /dev/ttyUSB2
picocom v3.1

port is        : /dev/ttyUSB2
flowcontrol    : none
baudrate is    : 9600
parity is      : none
databits are   : 8
stopbits are   : 1
escape is      : C-a
local echo is  : no
noinit is      : no
noreset is     : no
hangup is      : no
nolock is      : no
send_cmd is    : sz -vv
receive_cmd is : rz -vv -E
imap is        :
omap is        :
emap is        : crcrlf,delbs,
logfile is     : none
initstring     : none
exit_after is  : not set
exit is        : no

Type [C-a] [C-h] to see available commands
Terminal ready
AT+CUSD=1,"*222#",15
AT+CUSD=1,"*222#",15
ERROR
```

**Comment by obsy** [comment]
sms tool also uses these ussd commands, so if they don't work, sms_tool won't work. Sorry.

**Comment by Nowaker** [comment]
AT commands depend on the modem. In my case, Sierra MC7655, the commands are different. I've been experimenting with AT commands based on the instruction at https://www.manualslib.com/manual/531004/Sierra-Wireless-Mp-700-Series.html?page=83#manual but no results so far. Dumping some info for now...

```
AT+CMGF=1
OK

AT+CSCS="GSM"
OK

AT+CSCA?
+CSCA: "+13123149810",145

OK

AT+CMGS="1XXXXXXXXXX" 
> testing

+CMGS: 14

OK
```

Yet, no text sent.

And the message center appears to be correct - equals to the one from https://www.att.com/support/article/wireless/KM1108200/


I also tried with `AT+CMGF=0`, then `AT+CMGS=[length]`, where `length` is provided after encoding the message at https://www.smsdeliverer.com/online-sms-pdu-encoder.aspx. Still no result.

**Comment by Nowaker** [comment]
OK, it appears it won't be able to send messages since I use LTE.

http://smstools3.kekekasvi.com/topic.php?post=4844#post4844
