### ISSUE TITLE
Does it work with ModemManager?

### ISSUE THREAD

**Issue by bam80** [obsy/sms_tool#7]
Hi, I'm going to use ModemManager for LTE broadband internet access (via QMI).
Can I use `sms_tool` along with it to handle SMS?

**Comment by obsy** [comment]
If the modemmanager will not block interface for tsms_tool then yes.

**Comment by bam80** [comment]
That was the question actually :)

**Comment by obsy** [comment]
I have never tried to run sms_tool with a modmanager.

**Comment by bam80** [comment]
I see ModemManager has all the needed interfaces to implement SMS handling:
https://www.freedesktop.org/software/ModemManager/doc/latest/ModemManager/gdbus-org.freedesktop.ModemManager1.Modem.Messaging.html

Do you think your tool could make use of it one day, or it should be completely different project?

PS:
there are C/Python examples for SMS handling:
https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/tree/main/examples

**Comment by obsy** [comment]
```mmcli -V
mmcli 1.16.6
Copyright (2011 - 2021) Aleksander Morgado
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

mmcli --help-sms
Użycie:
  mmcli [OPCJA…] - Control and monitor the ModemManager

SMS options:
  --send                                                         Send SMS.
  --store                                                        Store the SMS in the device, at the default storage
  --store-in-storage=[Storage]                                   Store the SMS in the device, at the specified storage
  --create-file-with-data=[File path]                            Create a file with the data contents of the SMS.
```
modemmanager has its own implementation for SMS

**Comment by bam80** [comment]
The problem is [Luci-app-sms-tool](https://eko.one.pl/forum/viewtopic.php?id=20096) doesn't know about `mmcli` tool..  
I'll try some workaround to make MM release modem's serial ports. Will report how it goes.

**Comment by bobmorane83** [comment]
Hi all,
Any news on this topic ?
Tx

**Comment by bam80** [comment]
I ported OpenWrt to my router, so now I have possibility not to use MM at all. 
You can try it with MM yourself and report here, should work as long as MM doesn't block serial modem interface. (I don't remember details, please google for that)

**Comment by bobmorane83** [comment]
Never mind.
Thanks for answering.

**Comment by obsy** [comment]
Just ask someone to write plugin for modemmanager for LuCI.

**Comment by bam80** [comment]
FYI Kroks routers have the modemmanager for LuCI support by default, but it's semi-proprietary.

**Comment by obsy** [comment]
Which model?

**Comment by bam80** [comment]
All of them
