### ISSUE TITLE
sms_tool fails to be executed on Turris Omnia

### ISSUE THREAD

**Issue by xp499** [obsy/sms_tool#8]
Hi, sms_tool binary does fail to be executed on a Turris Omnia (Marvell 385 Armada, armv7 arch with dual-core ARM Cortex-A9) with system TurrisOS (openWRT based) up-to-date until today, with following message:

`Error relocating /usr/bin/sms_tool: __gmtime64: symbol not found`
`Error relocating /usr/bin/sms_tool: __timegm_time64: symbol not found`

Using latest github sms-tool_2021-12-03-d38898f4-1_arm_cortex-a9_vfpv3-d16.ipk from https://github.com/4IceG/luci-app-sms-tool releases page package.

I also opened an issue at that repo there but author pointed me to ask here about: https://github.com/4IceG/luci-app-sms-tool/issues/11

Any hints?

**Comment by obsy** [comment]
This is not my compilat. Just recompile package by yourself in turris' SDK; TurrisOS uses some different settings for system and you cannot use packages from pure openwrt.

**Comment by Nowaker** [comment]
@xp499 Works for me on my Omnia: https://dl.eko.one.pl/openwrt-19.07/packages/arm_cortex-a9_vfpv3-d16/base/sms-tool_2021-12-03-d38898f4-1_arm_cortex-a9_vfpv3-d16.ipk

```
# sms_tool -d /dev/ttyUSB2 -s ME status
Storage type: ME, used: 0, total: 255
```

**Comment by bernikr** [comment]
I get the same issue on a Linksys WRT1900ACS running OpenWrt 19.07.5 also using the provided `sms-tool_2021-12-03-d38898f4-1_arm_cortex-a9_vfpv3-d16.ipk` image:

```
root@OpenWrt:~# sms_tool -d /dev/ttyUSB0 -s ME status
Error relocating /usr/bin/sms_tool: __gmtime64: symbol not found
Error relocating /usr/bin/sms_tool: __timegm_time64: symbol not found
```

**Comment by obsy** [comment]
Use my package from https://dl.eko.one.pl/openwrt-19.07/packages/arm_cortex-a9_vfpv3-d16/base/

**Comment by bernikr** [comment]
thanks that solved my issue
